name: TestUnit
on: [pull_request]

jobs:
  test-unit:
    name: Test Units
    #    runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18' # The Go version to download (if necessary) and use.
      - run: make test-unit
