name: TestUnit
on: [pull_request]

jobs:
  test-unit:
    name: Test Units
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Run unit tests
        uses: cedrickring/golang-action/go1.16@1.6.0
        env:
          GO111MODULE: "on"
        with:
          args: make test-unit
  test-sim:
    name: Test Simulations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Run simulation tests
        uses: cedrickring/golang-action/go1.16@1.6.0
        env:
          GO111MODULE: "on"
        with:
          args: make test-sim-nondeterminism-fast
